### ISSUE TITLE
can not get data on EIP_2EET_SEX_NB_A!!!

### ISSUE THREAD

**Issue by msgoussi** [ilostat/Rilostat#2]
Rilostat::get_ilostat(id = "EIP_2EET_SEX_NB_A", type = "both", cache = FALSE) 
Error in utils::download.file(base, tfile, quiet = quiet) : 
  cannot open destfile 'C:\Users\310677\AppData\Local\Temp\RtmpG8YvlI/ilostat/indicator-EIP_2EET_SEX_NB_A-both-raw-7/1/2022 16:56.csv.gz', reason 'No such file or directory'

**Comment by dbescond** [comment]
server side issue, fixed
