### ISSUE TITLE
Connection issues when running standard example code

### ISSUE THREAD

**Issue by gronert-m** [ilostat/Rilostat#3]
Dear ILO Team,

I am trying to run the code for the "World Map of NEET" to emulate an example (from here: https://ilostat.github.io/Rilostat/articles/RilostatVisu.html).

This gives me (and my colleague next door, checked on another computer) the same error (although we have the same firewall):

![image](https://github.com/ilostat/Rilostat/assets/63501500/95d2ecd9-5273-48e9-a250-caaa71fa32d1)

This error appears for all things I try so it sounds like there is a general connection issue. I kindly ask for your help.

Best,

Mario

**Comment by dbescond** [comment]
that was server (for migration) issue in the ilo.

**Comment by gronert-m** [comment]
@dbescond , great, thanks!
