### ISSUE TITLE
Rilostat package cannot open table of contents

### ISSUE THREAD

**Issue by KateSchneider-FoodPol** [ilostat/Rilostat#4]
`toc <- get_ilostat_toc(segment = getOption("ilostat_segment", "indicator"),
                              lang = getOption("ilostat_lang", "en"),
                              search = getOption("ilostat_search", "none"),
                              filters = getOption("ilostat_filter", "none"),
                              fixed = getOption("ilostat_fixed", TRUE))`

Returns the following error: 

> Error in readRDS(con, refhook = refhook) : cannot open the connection to 'https://webapps.ilo.org/ilostat-files/Documents/rds/indicator/table_of_contents_en.rds'

Similarly I cannot pull data: 
`Rilostat::get_ilostat("UNE_DEAP_SEX_GEO_RT_A")`

Gives the same error:

> Error in readRDS(con, refhook = refhook) : cannot open the connection to 'https://webapps.ilo.org/ilostat-files/Documents/rds/indicator/table_of_contents_en.rds'

Please check the server. Thanks!

**Comment by KateSchneider-FoodPol** [comment]
https://webapps.ilo.org/ilostat-files/Documents/rds/indicator/table_of_contents_en.rds is returning a 404 error. This seems to be the problem. Your rapid resolution would be appreciated.

**Comment by ilostat** [comment]
fixed by updating the package (vs 2.2)
